# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Tekon Nightly Build

on:
  pull_request:
  workflow_dispatch:
  pull_request_target:
    branches:
      - tekton
  schedule:
    # HPE-images ran on 0 0 * * * lets run this one hour after
    - cron: "0 1 * * *"

jobs:
  image-update:
    name: Tekon Nightly Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup G Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Print gcloud info
        run: 'gcloud info'

      - name: Docker creds
        shell: bash
        run: gcloud auth configure-docker

      - name: GKE Credentials
        id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          location: ${{ secrets.CLUSTER_LOCATION }}

      - name: install TKN CLI
        shell: bash
        run: |
          curl -sfLo tkn https://github.com/tektoncd/cli/releases/download/v0.24.0/tkn_0.24.0_Linux_x86_64.tar.gz
          chmod +x ./tkn

      - name: connect to bastion
        shell: bash
        run: |
          gcloud compute ssh --zone ${{ secrets.BASTION_ZONE }} ${{ secrets.BASTION_NAME}} --tunnel-through-iap --project ${{ secrets.GCP_PROJECT_ID }} -- -N -D 8118 &
          echo "HTTPS_PROXY=socks5://localhost:8118" >> $GITHUB_ENV
          sleep 30

      - name: Run Tekton Build
        shell: bash
        run: | 
          kubectl apply -f tekton/common/
          kubectl apply -f tekton/go/
          tkn pipeline start trusted-cert-build-pipeline --use-pipelinerun trusted-cert-pipeline-run
